# Generated by Django 5.2 on 2025-05-27 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Регистрация'), ('forgot_password', 'Забыли пароль'), ('password_reset', 'Сброс пароля'), ('phone_update', 'Обновление телефона'), ('delete_account', 'Удаление аккаунта')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_confirmation',
            },
        ),
    ]
