# Generated by Django 5.2 on 2025-06-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_multibankauthtoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multibankauthtoken',
            name='user',
        ),
    ]
