# Generated by Django 5.2 on 2025-06-03 20:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_remove_multibankauthtoken_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultibankTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(null=True)),
                ('store_id', models.SmallIntegerField(null=True)),
                ('transaction_type', models.CharField(choices=[('donation', 'Донат'), ('fundraising', 'Сбор средств')], max_length=15, null=True)),
                ('card_token', models.TextField(null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_multibank_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_multibank_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'multibank_transaction',
            },
        ),
    ]
