# Generated by Django 5.2 on 2025-06-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_multibanktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='multibanktransaction',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачено')], default='new', max_length=10, null=True),
        ),
    ]
