# Generated by Django 5.2 on 2025-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_multibanktransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='multibanktransaction',
            name='transaction_id',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
