# Generated by Django 5.2 on 2025-06-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_multibanktransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multibanktransaction',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('paid', 'Оплачено'), ('failed', 'Провалено')], default='new', max_length=10, null=True),
        ),
    ]
