# Generated by Django 5.2 on 2025-06-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_alter_multibanktransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsconfirmation',
            name='purpose',
            field=models.CharField(choices=[('register', 'Регистрация'), ('login', 'Авторизация'), ('forgot_password', 'Забыли пароль'), ('password_reset', 'Сброс пароля'), ('phone_update', 'Обновление телефона'), ('delete_account', 'Удаление аккаунта')], max_length=20),
        ),
    ]
