# Generated by Django 5.2 on 2025-06-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_alter_smsconfirmation_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multibanktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('donation', 'Донат'), ('fundraising', 'Сбор средств'), ('subscription', 'Подписка')], max_length=15, null=True),
        ),
    ]
