# Generated by Django 5.2 on 2025-06-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_alter_multibanktransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multibanktransaction',
            name='creator_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='multibanktransaction',
            name='sapi_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='multibanktransaction',
            name='amount',
            field=models.BigIntegerField(null=True),
        ),
    ]
