# Generated by Django 5.2 on 2025-06-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ожидает модерации'), (1, 'Проигнорирована'), (2, 'Пост заблокирован'), (3, 'Креатор заблокирован')], default=0),
        ),
    ]
