# Generated by Django 5.2 on 2025-05-29 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='minimum_message_donation',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.PositiveBigIntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_received', to=settings.AUTH_USER_MODEL)),
                ('donator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donation',
                'indexes': [models.Index(fields=['donator'], name='donation_donator_9a2e55_idx'), models.Index(fields=['creator'], name='donation_creator_285434_idx')],
            },
        ),
    ]
