# Generated by Django 5.2 on 2025-05-30 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_minimum_message_donation_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_amount', models.PositiveBigIntegerField()),
                ('goal', models.PositiveBigIntegerField()),
                ('minimum_donation', models.PositiveBigIntegerField()),
                ('deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundraising', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fundraising',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='fundraising',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='authentication.fundraising'),
        ),
    ]
