# Generated by Django 5.2 on 2025-05-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_fundraising_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraising',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='minimum_donation',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
