# Generated by Django 5.2 on 2025-06-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_fundraising_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_owner',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
