# Generated by Django 5.2 on 2025-06-03 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_card_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='authentication.card'),
        ),
        migrations.AddField(
            model_name='user',
            name='sapi_share',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
