# Generated by Django 5.2 on 2025-06-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_donation_card_user_sapi_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
