# Generated by Django 5.2 on 2025-06-05 06:47

import apps.authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_pinfl'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.authentication.managers.UserManager()),
                ('all_objects', apps.authentication.managers.AllUserManager()),
            ],
        ),
    ]
