# Generated by Django 5.2 on 2025-06-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_reason',
            field=models.CharField(choices=[('copyright', 'Контент, нарушающий авторские права третьих лиц'), ('extremism', 'Материалы экстремистского, террористического характера'), ('discrimination', 'Дискриминация по расовому, половому, религиозному и другим признакам'), ('pornography', 'Порнографические материалы и контент для взрослых'), ('violence', 'Агрессивный, жестокий или призывающий к насилию контент'), ('drugs_alcohol', 'Призывы к употреблению наркотических веществ и алкоголя'), ('misleading', 'Введение пользователей в заблуждение (мошенничество, спам, фейковые сборы средств)'), ('personal_data', 'Контент, содержащий личные данные третьих лиц без их согласия'), ('other', 'Другое')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
