# Generated by Django 5.2 on 2025-06-23 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_block_reason_user_is_blocked_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_blocked_by_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_blocked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
