# Generated by Django 5.2 on 2025-06-25 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_user_is_blocked_by_admin_user_is_blocked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW_STATISTICS', 'Просмотр Статистики'), ('VIEW_SENDING_NOTIFICATIONS', 'Просмотр рассылок уведомлений'), ('MODIFY_SENDING_NOTIFICATIONS', 'Редактирование рассылок уведомлений'), ('VIEW_REPORTS', 'Просмотр жалоб'), ('MODIFY_REPORTS', 'Редактирование жалоб'), ('VIEW_CREATORS', 'Просмотр креаторов'), ('MODIFY_CREATORS', 'Редактирование креаторов'), ('VIEW_CHATS', 'Просмотр чата поддержки'), ('MODIFY_CHATS', 'Редактирование чата поддержки'), ('VIEW_ADMINS', 'Просмотр администраторов'), ('MODIFY_ADMINS', 'Редактирование администраторов')], max_length=55)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_permission',
            },
        ),
    ]
