# Generated by Django 5.2 on 2025-06-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_user_first_name_user_is_admin_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='block_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpermissions',
            name='permission',
            field=models.CharField(choices=[('VIEW_STATISTICS', 'Просмотр статистики'), ('MODIFY_STATISTICS', 'Редактирование статистики'), ('VIEW_SENDING_NOTIFICATIONS', 'Просмотр рассылок уведомлений'), ('MODIFY_SENDING_NOTIFICATIONS', 'Редактирование рассылок уведомлений'), ('VIEW_REPORTS', 'Просмотр жалоб'), ('MODIFY_REPORTS', 'Редактирование жалоб'), ('VIEW_CREATORS', 'Просмотр креаторов'), ('MODIFY_CREATORS', 'Редактирование креаторов'), ('VIEW_CHATS', 'Просмотр чата поддержки'), ('MODIFY_CHATS', 'Редактирование чата поддержки'), ('VIEW_ADMINS', 'Просмотр администраторов'), ('MODIFY_ADMINS', 'Редактирование администраторов')], max_length=55),
        ),
    ]
