# Generated by Django 5.2 on 2025-06-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_user_block_desc_alter_userpermissions_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
