# Generated by Django 5.2 on 2025-06-27 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_user_temp_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscriber_card',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='authentication.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
