# Generated by Django 5.2 on 2025-06-29 07:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_alter_notificationdistribution_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationdistribution',
            name='type',
        ),
        migrations.AddField(
            model_name='notificationdistribution',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('push_notification', 'Push-уведомление')], max_length=55), default=list, size=None),
        ),
    ]
