# Generated by Django 5.2 on 2025-05-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=300, null=True)),
                ('gen_name', models.CharField(max_length=100, null=True)),
                ('size', models.FloatField(null=True)),
                ('path', models.TextField(null=True)),
                ('content_type', models.CharField(max_length=100, null=True)),
                ('extension', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
