# Generated by Django 5.2 on 2025-06-11 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('can_chat', models.CharField(choices=[('everyone', 'Все'), ('nobody', 'Никто'), ('subscribers', 'Только подписчики определенного уровня'), ('donations', 'Только сообщения с донатом')], default='everyone', max_length=11)),
                ('subscription_plans', models.JSONField(default=list)),
                ('minimum_message_donation', models.PositiveBigIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_settings',
            },
        ),
    ]
