# Generated by Django 5.2 on 2025-06-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsettings',
            name='minimum_message_donation',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chatsettings',
            name='subscription_plans',
            field=models.JSONField(default=list, null=True),
        ),
    ]
